# Generated by Django 5.1.2 on 2024-10-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='precio_actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='saving',
            name='date',
            field=models.DateField(),
        ),
    ]
